更新github action

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -36,13 +36,26 @@ jobs:
 
       - name: Remove existing doxygen symlink if it exists
         run: |
-          sudo rm -f /usr/local/bin/doxygen
+          if [ -L /usr/local/bin/doxygen ]; then
+            sudo rm -f /usr/local/bin/doxygen
+          elif [ -f /usr/local/bin/doxygen ]; then
+            sudo rm -f /usr/local/bin/doxygen
+          fi
+
+      - name: Check if doxygen symlink is removed
+        run: |
+          if [ -L /usr/local/bin/doxygen ]; then
+            echo "Symlink still exists, failed to remove"
+            exit 1
+          fi
 
       - name: Setup Doxygen symlink
         run: |
-          if [ ! -f /usr/local/bin/doxygen ]; then
-            sudo ln -s /opt/doxygen-1.9.2/bin/doxygen /usr/local/bin/doxygen
-          fi
+          sudo ln -s /opt/doxygen-1.9.2/bin/doxygen /usr/local/bin/doxygen
+
+      - name: Verify doxygen installation
+        run: |
+          which doxygen
           doxygen --version
 
       - name: Make gen_pack.sh executable
